== Un Extracto del Diario de David Ferris

Cuando considero la condición del hombre en su estado caído,
y el gran cambio que experimentan todos los que han sido librados del
poder de las tinieblas y trasladados al reino del amado Hijo de Dios;
y cuán necesario es para alcanzar ese estado feliz,
que todos experimenten la muerte de sus pasiones naturales y de sus inclinaciones malignas;
que experimenten que el "`viejo hombre`" es matado
y que son revestidos del "`nuevo hombre`",
el cual es creado según Dios en justicia y verdadera santidad;
y que para poder andar en el camino nuevo y vivo,
debemos experimentar que las cosas viejas pasaron y que todas las cosas son hechas nuevas;
quiero decir, cuando considero estas cosas, siento interés por mis semejantes,
de que lleguen a alcanzar este cambio.
Y sabiendo que tengo algo de experiencia de esto,
por haber pasado por diferentes dispensaciones de prueba y aflicción,
me siento movido a dejar un relato de ellas a la posteridad,
a fin de mostrarles a los que vienen que el Señor siempre está cerca,
y será hallado por los que temprano lo buscan;
que es muy paciente para con los que se extravían,
y misericordioso con todos los que sinceramente se vuelven a Él.
Es mi esperanza que esto les suministre información y ánimo a los
viajeros cansados que están en este mismo camino,
y los induzca a cumplir alegremente los requerimientos divinos.

Escribí un corto relato de la primera parte de mi vida en latín
y lo extendí hasta alrededor de los veinticinco años de mi edad.
La gran cantidad de dificultades y peligros en mi camino,
y la duda de si sería o no capaz de mantenerme hasta el fin,
me indujeron a escribir mi historia en un lenguaje desconocido para los que me rodeaban.
Concluí que si me mantenía en mi camino, podría traducirlo más adelante al inglés,
y añadirle más, conforme sintiera libertad.
Ahora, después de casi veinte años de experimentar la ayuda y la preservación divinas,
y teniendo grandes motivos para decir que "`Dios es bueno al alma que
lo busca,`" que nadie lo busca en vano y que Sus misericordias nunca fallan;
me siento inclinado a traducirlo, esperando que sea útil,
al menos para algunos de mi posteridad.

Nací en Stratford, en Connecticut, Nueva Inglaterra, el décimo día del tercer mes, 1707.
Mis padres, Zacarías y Sarah Ferris,
profesaban su religión junto a las personas que eran llamadas Presbiterianas,
y me educaron en esa forma.
Cuando era muy joven, mi padre se mudó a un lugar llamado New Milford.
Un lugar que acababa de ser establecido,
y por ende yo no tenía la ventaja de asistir a una escuela;
pero bajo el cuidado de mi madre,
aprendí rápidamente a leer la Biblia y entendí que había un Ser Supremo,
que hizo todas las cosas, y que Él las preservaba y sostenía en el orden establecido,
y que a mí, como hechura de Sus manos,
me correspondía rendirle cuentas de cada aspecto de mi conducta.
Cuando tenía cerca de ocho años de edad,
me informaron que el Ser Divino era auto-existente, sin principio ni fin;
y al no tener la capacidad de entender cómo era posible,
a veces pensaba tan intensamente en el tema, que quedaba muy desconcertado.
Finalmente se me mostró, que la proposición era demasiado elevada para mi comprensión,
y recibí algo así como una reprensión por ponerme
a investigar cosas que estaban más allá de mi capacidad.
Desde ese entonces, me daba miedo entrometerme en misterios tan profundos como estos.

Mi madre,
siendo una mujer piadosa que se preocupaba mucho por el
bienestar de sus hijos (tanto temporal como espiritual),
frecuentemente nos daba buenos consejos y advertencias,
deseando que nos apartáramos de la sendas del error;
y por medio de su ejemplo y preceptos, nos enseñaba a andar en los caminos de la virtud,
los cuales conducen a la paz.
Eso fue de gran ayuda para nosotros cuando éramos jóvenes,
y no pudimos olvidarlo fácilmente cuando llegamos a la madurez.
La muerte era un tema frecuente en mis pensamientos, y a los doce años de edad,
sentía al Espíritu Santo llamándome frecuentemente a abandonar el mal,
a dejar las vanidades juveniles en las que me deleitaba en aquel entonces,
y a ser sobrio y cuidadoso en todos mis caminos.
Por prestar atención al llamado divino y a las reprensiones
de la instrucción que me eran comunicadas diariamente,
fui guardado del mal; y vi algo de la hermosura de la santidad,
del estado feliz de los justos en el mundo por venir,
y de la angustiante situación de los impíos cuando son despojados de la mortalidad,
y escuchan que se pronuncia contra ellos la terrible sentencia: "`¡Apartaos, malditos!`"

Alrededor de este tiempo sucedió una pequeña circunstancia que
afectó mucho mi mente y me proporcionó una enseñanza permanente.
Cuando cabalgaba a través de un río, contra una corriente rápida,
un perro joven que trataba de nadar detrás de mí, no pudo mantenerse junto a mi caballo,
pues la corriente era demasiado fuerte para él. Se
veía que estaba en una angustia muy grande,
incluso hasta la desesperación. Conforme mi mente
se llenaba de compasión por el pobre animal,
se presentó ante mis ojos el espantoso asombro en el que una pobre alma se encontraría,
cuando dejara el mundo sin ninguna esperanza.
Tan simple como parezca este suceso, creo que fue de utilidad para mí por mucho tiempo.
Por varios años tuve mucho cuidado con mis pensamientos, palabras y acciones;
el temor del Señor me preservó del mal.
Mi mente se mantuvo humilde bajo el sentido de mi necesidad diaria de ayuda divina;
y mientras permanecí interesado en una vida religiosa,
prestando atención a "`las reprensiones que instruyen que son el camino de vida,`"^
footnote:[Proverbios 6:23]
me era ministrado un incremento de luz y vida,
de modo que llegué a deleitarme en la virtud.
A medida que se incrementaban mis deseos y mi interés por las cosas divinas,
se me abría el conocimiento de ellas.
Yo podía decir verdaderamente, que el Señor era mi deleite.
Y por algunos años, mientras moré en Su temor, Su yugo era fácil para mí,
Su carga ligera y todas las vanidades infantiles me eran una carga.

Mientras me mantuve cerca del Manantial de Vida, con mi mente puesta en lo verdadero,
el mundo y las cosas del mundo perdieron todo su esplendor.
Pero, ¡ay! al no mantener mis ojos puestos únicamente en la luz, perdí mi Líder;
y poco a poco el mundo volvió a levantarse con esplendor ante mi vista.
Los deleites y las vanidades terrenales se apoderaron tanto de mis afectos,
que me complacía mucho estar acompañado de personas vanas y ligeras.
Eso fue una pérdida indescriptible para mí,
y lo menciono para que otros reciban advertencia a través de mi ruina.
Parece algo casi milagroso que yo haya sido restaurado de ese estado caído. Mi
madre se lamentaba por mí y a menudo me aconsejaba e instaba a que volviera,
mostrándome el peligro de un camino de vanidad como ese.
A pesar de esto, mi Monitor interno y Guía anterior no me abandonó completamente.
Él a veces me reprendía, otras veces me llamaba,
persuadiéndome y contendiendo conmigo para que regresara.
Algunas veces, durante mi vanidad, veía que estaba en el camino hacia la muerte,
y que ese camino me llevaría a la confusión eterna si no lo abandonaba.

Algunas veces mi inquietud era tan grande,
que me veía obligado a dejar a mis compañeros y a
apartarme tan lleno de angustia y estrés,
que no sentía ninguna satisfacción hasta mucho tiempo
después. Durante esos tiempos de aflicción,
estaba dispuesto a prometer que dejaría mi vano curso de vida,
y a hacer pacto con el Señor de que no lo haría más,
con tal de que a Él le placiera concederme Su ayuda.
Pero como mis esfuerzos dependían demasiado de mis propias fuerzas, probaron ser inútiles.
La vanidad prevaleció tanto, que comencé a deleitarme mucho en la música,
en el baile y en otros vanos entretenimientos.

A los veinte años de edad me dio una enfermedad tan grave, que tanto yo,
como los que estaban alrededor de mí, teníamos muy poca esperanza de que me recuperara.
En ese entonces la muerte me miró fijamente a la cara y una terrible escena de aflicción,
angustia y miseria se presentó ante mis ojos.
Se me mostró claramente que si yo hubiera sido quitado
del escenario de acción en ese momento,
me hubiese perdido inevitablemente,
y que los espíritus malignos habrían estado esperando alrededor de mí,
para llevar mi alma a las mansiones de miseria y de oscuridad eterna;
de modo que mi horror, ansiedad y angustia eran inexpresables.
En el momento de mayor angustia clamé al Señor pidiendo
ayuda y le prometí que enmendaría mis caminos,
si me concedía más tiempo y capacidad.
Y le plació a la bondadosa Providencia tener misericordia de mí,
de modo que fui restaurado y sanado, y en aproximadamente un mes pude caminar.

Después de mi recuperación recordé la angustia en
la que había estado y la promesa que había hecho,
cuando estuve bajo la terrible percepción de mi miseria y destrucción eterna.
Vi la necesidad de cumplir fielmente mis votos.
Estaba consciente de que había una obra por hacer,
y que si no cumplía entonces mi promesa, pasaría por la misma, o más bien,
por una peor escena de miseria y angustia.
Me parecía improbable que me fuera concedida una oportunidad
más conveniente para el arrepentimiento que esa,
y concluí que ese era el momento de apartarme de la vanidad,
dejar mis malos caminos y renunciar a todos mis deleites carnales.
Pero cuando me determiné a empezar esta necesaria obra de transformación,
el adversario de todo bien me tentó a creer que ya era demasiado
tarde para pensar en obtener paz con mi Creador,
por esta simple razón:
Que dado que los hombres tenían un día o tiempo en el que podían ser salvos;
si dejaban pasar esa oportunidad sin aprovecharla,
sería en vano que lo intentaran después. Él me decía que yo había
tenido ese día de visitación y que lo había dejado pasar;
que había sido favorecido con ayuda de una forma poco común y que no la había aceptado;
que había sido hecho partícipe del Espíritu Santo;
había gustado de la buena Palabra de Dios y de los poderes
del siglo venidero y había caído de todo eso;
por lo tanto, que era imposible que yo fuera renovado otra vez para arrepentimiento,
ya que había crucificado al Hijo de Dios nuevamente, exponiéndolo a vituperio.
Este razonamiento me pareció tan fuerte y tan acorde a la doctrina de los apóstoles,
que no argumenté más y concluí que era demasiado tarde para
intentar regresar con alguna esperanza de ser aceptado.

Desde ese momento, durante aproximadamente dos meses, nunca busqué misericordia,
sino que permanecí en total desesperación. Mi angustia era tan grande
como podía soportar sin perder la razón. Deseaba la muerte diariamente,
queriendo que ocurriera sin tener que poner violentamente mis manos sobre mí mismo,
algo que no me sentía muy tentado a hacer.

Era común que los jóvenes de nuestro vecindario pasaran mucho tiempo en vanidad y diversión,
olvidando a Dios su Creador,
como si hubieran sido creados para complacerse a
sí mismos satisfaciendo sus mentes carnales.
Y, siempre y cuando ellos no fueran demasiado impíos,
los ancianos de la sociedad no se preocupaban mucho por esto.
Pero en el año 1727,
hubo una gran reforma en New-Milford entre los jóvenes de la religión Presbiteriana.
Ellos fueron despertados por la operación directa
del Espíritu Santo en sus propias mentes,
lo cual los llevó a una gran preocupación por su bienestar futuro,
en la cual no tenían ninguna ayuda externa.
La doctrina apostólica de "`Cristo en el interior`"
y de ser "`guiados por el Espíritu de Dios`",
era negada por los sacerdotes y por muchos del pueblo,
quienes parece que tenían muy poca experiencia del Maestro Divino en su interior.
Ellos afirmaban que la revelación ya había cesado
y que nada de eso se experimentaba en el presente.
Como yo había sido compañero de esos jóvenes en la vanidad y desenfreno,
ellos (sin saber nada de mi condición interna,
que no le había descubierto a nadie) generalmente
acudían a mí para obtener consejo y asesoramiento.
Estaba muy preocupado por ellos y deseaba proporcionarles ayuda,
aunque en ese entonces no tenía esperanza de obtener alivio para mí mismo.

Mi angustia continuaba y se incrementaba, de modo que nada me satisfacía en esta vida.
Un día, durante ese periodo de desesperación y angustia profunda,
decidí dejar mi tierra natal e ir a algún país extranjero,
donde intentaría pasar el resto de mis días como un desconocido,
para que ninguno de mis parientes o conocidos supieran qué había
sido de mí. Ante mis propios ojos era una criatura pobre,
perdida y reprobada,
por lo que no estaba dispuesto a quedarme en casa
para ser una desgracia para mis parientes y compatriotas.
Ese fue el día de la más profunda aflicción y angustia que había conocido.
Hacia el atardecer, cuando iba detrás del arado, mi atención fue capturada,
por así decirlo, por una voz suave y delicada, que decía:
"`La sangre de Jesucristo Su Hijo limpia de todo pecado.`"^
footnote:[1 Juan 1:7]
Pero la desprecié, diciendo en mi corazón: "`Es demasiado tarde,
hubo un día en el que yo pude haber sido limpiado, pero ¡ay,
lo he dejado pasar para siempre!`"

Un rato después, tal vez como media hora más tarde,
mientras consideraba a qué tierra debía huir,
las mismas palabras pasaron por mi mente otra vez con más autoridad que antes,
y demandaron mi atención aún más fuertemente que antes.
Pero las volví a rechazar,
concluyendo que había perdido todo el derecho de aplicarme esas palabras,
y entonces continué con la consideración de mi huida a una tierra extranjera.
Mientras tanto mi dolor y ansiedad mental se incrementaban,
de modo que ya no era muy capaz de soportarla o de seguir con mis asuntos.
Pero mientras seguía reflexionando,
las mismas palabras (sin que las buscara y de manera inesperada) pasaron
por mi mente con mayor poder y autoridad que todas las veces anteriores:
"`La sangre de Jesucristo Su Hijo limpia de todo pecado.`"
Esa vez,
al sonido de esas palabras mi alma saltó de alegría.
Sentí que se abrió una puerta de esperanza,
y dije en mi corazón, "`Si Él puede limpiar de _todo_ pecado,
¿por qué no el mío?`" Entonces brotó una esperanza viva en mi alma.
Vi que Sus brazos de misericordia estaban abiertos para recibirme,
y que un camino fue abierto delante de mí como una senda a través de la espesura.

Me llené de un gozo indecible.
Acciones de gracias y alabanzas vivas a mi Redentor,
se levantaron en mi corazón por haber experimentado una redención tan grande y maravillosa.
Que mis pies hayan sido sacados del cieno y puestos sobre una roca; y que yo,
que antes de eso no tenía ninguna esperanza,
haya sido favorecido con una bien cimentada seguridad de perdón y aceptación,
fue una misericordia que nunca olvidaré.

En ese tiempo comencé a buscar ayuda divina, y en infinita bondad,
una mano de ayuda fue extendida para mi restauración y para sanar mis rebeliones.
Entonces pude cantar en las orillas de la redención
y alabar el nombre de Aquel que vive para siempre.
El Espíritu Santo, el maestro bendito con el cual había sido favorecido en el pasado,
pero que había abandonado,
fue restaurado como líder y maestro para dirigirme
e instruirme en el camino de paz y descanso.

Después de ese favor tan grande, mi mente se humilló y sujetó a la cruz de Cristo,
y yo me dispuse con todo mi corazón a tomarla cada día y a seguirlo a
Él (mi bondadoso líder) en el camino angosto de la negación a mí mismo.
Y conforme era obediente, Él me llevaba a dejar el curso vano de mi vida,
y todos aquellos deleites juveniles y placeres carnales
que eran desagradables a mi querido Señor y Maestro;
quien por Su maravillosa misericordia,
me había sacado del calabozo y había escuchado mis
oraciones en un tiempo de profunda aflicción. Entonces,
Él se convirtió en mi director en todas las cosas,
pues me mostraba claramente cuáles eran mis deberes
y me capacitaba para realizarlos de manera aceptable;
pero si en algún momento actuaba en mi propia voluntad,
perdía mi fuerza y no encontraba ninguna aceptación
o beneficio por las cosas que había hecho.
Poco a poco aprendí que no podía hacer nada de manera aceptable,
sin la ayuda directa del Espíritu de Cristo el Redentor.
Por esto sentía una necesidad de acudir continuamente a Él--mi único y
suficiente Ayudador--y de esperar humildemente Su ayuda y dirección,
y conforme era fiel, Él me guiaba en la senda de vida que me llevaría a la paz eterna,
si continuaba en ella.

Habiendo aprendido poco a poco que nada de una naturaleza religiosa
podía hacerse efectivamente sin la ayuda directa del Espíritu Santo,
pude reconocer humildemente que había sido maravillosamente
favorecido con instrucción Divina,
mucho más allá de mis expectativas e infinitamente más de lo que merecía. Era llevado
(por así decirlo) de la mano y ayudado a superar cada dificultad que se me presentaba.
Pero el adversario de mi alma intentaba toda clase de estratagemas
para apartarme de la senda de la virtud.
Él se esforzaba noche y día por impedir que anduviera en ese camino angosto,
alegando que las dificultades eran tan grandes que nunca podría resistir hasta el fin,
y sugiriendo que todos mis esfuerzos serían en vano.
Parecía que él estaba presente continuamente, estuviera yo despierto o dormido,
pues inquietaba mi mente tanto como le era posible.
Pero mi oración pidiendo ayuda divina era incesante,
clamando que Uno más fuerte que él apareciera en mi ayuda y saqueara su casa.
Y en alrededor de un año,
después de haber sido levantado del pozo de la desesperación (como relaté anteriormente),
recibí una promesa de que el Dios de paz aplastaría en breve a Satanás bajo mis pies.^
footnote:[Romanos 16:20]
Se me concedió fe para creer en esta promesa, y esperaba una pronta redención,
pero el enemigo continuó afligiéndome con sus asaltos,
tentaciones y sugerencias malignas por unos meses después. Sin embargo,
seguí creyendo que el tiempo llegaría, según la promesa,
y oraba que se cumpliera en el tiempo del Señor.

Finalmente, Uno más fuerte que él vino y lo echó fuera, y lo desposeyó totalmente;
y no solo lo aplastó bajo mis pies, sino que lo echó muy lejos de mí. En ese momento,
el poder del enemigo para asaltar o para inquietarme de alguna manera fue removido;
y no era capaz de poner ninguna tentación delante de mí. Entonces mi alma se
llenaba diariamente de acciones de gracias y alabanzas vivas por esa redención,
como también por las muchas otras múltiples misericordias y favores de Dios,
que se me concedían día a día, siendo yo "`un gusano y no un hombre.`"^
footnote:[Salmos 22:6]

Puedo decir, para el honor del gran nombre de Aquel que hizo cosas maravillosas por mí,
y para la alabanza de Su gracia,
que al adversario de todo bien no solo se le impidió angustiarme en esta ocasión,
sino que la fuente de vida divina fue abierta y el agua que salía
de ella fluía tan libre y plenamente hacia mi alma,
que fui tan absorbido en ella y tan enamorado de ella, que todas las riquezas,
honores y placeres vanos de este mundo no tenían lugar en mis afectos.
En ese estado anhelaba estar con Cristo,
lo cual podía ver que era mejor que estar aquí. No sé si hubo un momento,
mientras estaba despierto, por casi dos años,
en el cual no pudiera cantar alabanzas vivas a Aquel que vive por siempre y para siempre.
Ninguna pérdida,
dificultad o decepción pudo (en ninguna medida) perturbarme en ese tiempo;
por lo menos no perceptiblemente para mí o para otros,
porque yo me deleitaba en cosas muy diferentes a las que este mundo puede dar o quitar.
Yo habitaba como en un monte, fuera del alcance del enemigo, y aparentemente,
fuera del peligro de cualquier mal.
Allí esperaba permanecer todos los días de mi vida, deseando nunca ser movido.

Independientemente de lo extraño que pueda parecer este relato para muchos,
creo que es absolutamente verdadero.
Estoy consciente de que algunos que no tienen experiencia en cosas de esta naturaleza,
podrían reírse de esta narrativa,
pero otros podrían alegrarse al encontrar en ella una descripción
de circunstancias que quizás correspondan a sus propias experiencias,
de las pruebas por las que han pasado y de los favores
que han recibido de la mano divina y bondadosa.
No escribo este relato con vanagloria sino con temor,
no sea que la siguiente parte de mi vida no corresponda con los
favores que me han sido dados por el bondadoso benefactor,
como declaré en la narrativa anterior.

Mientras moraba como en una montaña, como conté anteriormente,
mis ojos espirituales estaban abiertos y mi entendimiento era iluminado y ensanchado.
En aquel entonces me asombraba ver que el mundo (hasta donde llegaba mi
conocimiento de él) estaba mucho más en lo externo que en la sustancia,
era mucho mejor en apariencia que lo que era en realidad,
y que incluso la forma externa de piedad se veía muy poco.
Había formado la opinión de que las personas entre las cuales
fui educado eran mejores que otros profesantes del Cristianismo;
pero cuando mis ojos fueron ungidos de este modo para ver claramente,
encontré muy poca religión verdadera entre ellos.
Me parecía que la pureza primitiva estaba muy perdida,
y estaba lleno de dolor y lamento por causa de la gran caída que
había entre los profesantes de la religión cristiana en general.
Porque cuanto más me interesaba en examinar el asunto y buscaba sabiduría divina,
más fuertes eran mis convicciones y más claras mis observaciones,
de que había acontecido una apostasía general,
y que se consideraba muy poco la necesidad de llevar una
vida de negación al yo y de permanecer bajo la cruz de Cristo.

Antes de ese período, había tenido el deseo de aprender latín, griego y hebreo,
y realizar estudios superiores,
y entonces mi mente estaba convencida de que sería correcto para mí seguir ese curso;
pero antes de narrar mi progreso en ese proyecto,
regresaré a un asunto que mencioné antes de manera breve.
Dije que en el año 1727,
algunos de mis compañeros fueron llevados a una preocupación por su felicidad futura.
Esa preocupación se esparció e incrementó tanto entre los jóvenes de New-Milford,
que se convirtió en un fenómeno general.
En ese entonces,
muchos de los que habían pasado la mayoría de su tiempo en vanidad y entretenimiento,
estaban bajo un ejercicio por su bienestar eterno; clamando,
como algunos lo hicieron en el pasado: "`¿Qué haremos para ser salvos?`"
Creo que en aproximadamente un año,
unos sesenta nos unimos estrechamente a los presbiterianos
en su participación del pan y del vino.
Conforme éramos fieles en el cumplimiento de nuestro deber (hasta donde nos era manifestado),
y nos esforzábamos por avanzar en la senda de la virtud,
nuestros entendimientos eran iluminados,
tanto como para percibir algunas cosas en una luz diferente a esa en que
estas mismas cosas eran vistas por nuestros compañeros profesantes--tanto
con respecto a asuntos en la práctica como también en la doctrina.
Algunas veces nos atrevíamos a mencionar algunos de nuestros pensamientos
sobre temas en los que entendíamos que había una diferencia entre nosotros,
lo cual muy pronto nos metió en problemas.

Nos acusaron de tener opiniones heréticas,
y nos llevaron ante la iglesia para que respondiéramos a las acusaciones.
Ministros de los alrededores fueron llamados para tratar con nosotros en esa ocasión,
pero no hicieron casi nada.
Yo había declarado previamente por escrito, los puntos de diferencia entre nosotros,
junto con varias razones por las que no estábamos de acuerdo,
y cuando se reunió la congregación para tratar con nosotros,
les presenté lo que había escrito.
Se designó un comité para examinar el documento y
juzgar si era adecuado o no leerlo en la asamblea.
Cuando volvieron, el comité habló favorablemente y se leyó el documento delante de todos.
Cuando se presentaba alguna dificultad,
se me pedía que explicara lo que había querido decir, lo cual hacía correspondientemente.
Después de que se leyó todo, se sentaron en silencio por un tiempo.
Finalmente, un anciano se levantó y dijo:
"`Si esto es todo en lo que se supone que nuestros hermanos jóvenes difieren de nosotros,
no hay nada en este escrito a lo que yo no pueda unirme y decirle '`Amén`'.`"
Otros de entre los más respetados expresaron la misma opinión,
por lo cual se concluyó que nuestros pensamientos no eran tan heterodoxos
como para impedir nuestra comunión. Por consiguiente,
el asunto se resolvió y fuimos declarados miembros en plena comunión.

Pero a pesar de esa conclusión, se hizo circular un informe de que éramos herejes,
y en general, las personas lo creyeron.
Yo era considerado un líder entre ellos.
Algunos nos llamaban Cuáqueros, pero nosotros no sabíamos nada de esas personas,
y en ese momento pensábamos que era un título tan malo como pensaban ellos;
aunque considerábamos nuestro deber soportar pacientemente
el oprobio que echaban sobre nosotros por causa de la Verdad.

Pero para continuar con el relato de mis trámites relacionados con los estudios,
fui primero al maestro de nuestra parroquia y me quedé con
él como estudiante por aproximadamente un mes,
hasta que se negó a enseñarme más; alegando como razón de su negativa,
que mis opiniones eran demasiado herejes como para que me aceptaran en la universidad,
de modo que mi esfuerzo sería en vano, o al menos, no correspondería al fin propuesto.
Él era un hombre débil y tenía muy poca experiencia en asuntos religiosos,
en los cuales yo entonces había obtenido un poco de conocimiento, y además,
no tenía suficiente preparación como para enseñarme,
lo que hizo que estuviera dispuesto a dejarlo.

Después de eso decidí ir a Danby, como a treinta millas de la casa de mi padre,
para ponerme bajo la tutela de un maestro cuyo nombre era Moss.
Había escuchado que él era muy preparado y un buen cristiano.
Esas cualidades, pensaba,
harían que mi estadía fuera placentera para mí y no me decepcioné.
Pero mientras estaba preparándome para ir a él,
repentinamente me enfermé, y me puse tan mal,
que en pocas horas no se sabía con certeza si me recuperaría o no.
Pensaba que mi partida estaba cerca,
aunque en ese entonces no veía cómo trataría el Señor conmigo.

Mientras yacía muy enfermo (aunque mi entendimiento estaba quieto y despejado,
y mi voluntad entregada completamente) mi madre se me acercó
y me preguntó si pensaba que iba morir de esa enfermedad.
Le respondí que no sabía lo que acontecería,
pero que estaba contento de dejar este mundo si esa era la voluntad de Dios.
Después de conversar un rato, mi madre me dejó solo,
e inmediatamente después mi alma (según pude comprender) dejó el cuerpo,
por lo cual me llené de gozo y concluí que había
terminado con este mundo y con todas sus aflicciones.
Al estar libre de los grilletes de la mortalidad,
seguí adelante con regocijo hacia la tierra de bendición con mi alma muy alegre,
y mientras partía pensé haber visto mi cuerpo yaciendo
como un pedazo de materia sin vida.
Pero conforme seguía adelante,
me encontré con una excelente persona a quién tomé como el Hijo de Dios,
quien me informó que no debía seguir, diciendo: "`Debes regresar al cuerpo; no morirás,
sino que vivirás y declararás las maravillosas obras del Señor.`" Me inquietaba
pensar en regresar para ser confinado en un cuerpo de barro.
Sin embargo, me mantuve quieto, meditando y esperando dirección,
dispuesto a obedecer cuando se mostrara que ese era mi deber.
Entonces dije: "`Sea hecha la voluntad del Señor,`" e inmediatamente estaba en el cuerpo.

Poco tiempo después de eso,
mi madre regresó a la habitación y repitió la pregunta que me había hecho antes,
si pensaba que iba a morir en ese momento.
Respondí: "`No moriré de esta enfermedad.`"
Parecía sorprendida de que respondiera tan positivamente y sin titubear,
y entonces me preguntó cómo lo sabía. "`Porque,`" dijo,
"`hace como una hora me dijiste que no sabías si la vida
o la muerte iba a ser tu porción en este momento.`"
Entonces le conté lo que acababa de ocurrir,
lo cual aclaró sus dudas con respecto a mi respuesta tan segura.
Ella se llenó de alegría y de agradecido reconocimiento
a la Fuente de todo Bien por regresarme a ella,
y por ser tan bondadoso conmigo como para revelarme
Su voluntad de una manera tan clara e indubitable.
En ese momento mi madre y yo éramos Presbiterianos y continuamos
en esa denominación por varios años después de ese suceso.

Estando ya consiente de que Dios requería que continuara aquí por más tiempo,
me puse muy pensativo,
no fuera a ser que estuviera equivocado al suponer que había entendido bien la
voluntad de mi Maestro Divino con respecto a mi aprendizaje de idiomas,
etc.,
y fui llevado a examinar estrictamente si estaba cumpliendo o no mi deber al intentarlo.
Porque para ese momento había llegado a una perspectiva más clara
de la que tenía antes respecto al aprendizaje humano,
y de cómo era insuficiente para preparar a un hombre para el ministerio del Evangelio.
Estando humillado y sintiendo al yo completamente reducido,
estaba dispuesto (si descubría que mi meta era un error)
a reconocer mi falta ante Aquel que conoce todas las cosas,
a arrepentirme de mi apresuramiento y a confesar mi error,
especialmente ante aquellos a quienes les había dado
a conocer mis intenciones en el asunto.
Les había dicho a algunos de mis compañeros que veía que era mi deber adquirir conocimiento,
y por un tiempo considerable, antes de que hubiera alguna posibilidad de lograrlo,
había ido tan lejos como para atreverme a decir que lo obtendría. Por lo tanto,
si había estado equivocado,
entonces era necesario que lo supiera y que lo reconociera en todo lugar; como también,
de que tuviera más cuidado en el futuro de no dar
nada por sentado y luego reportarlo como una certeza.

Durante esa enfermedad, que continuó como tres semanas,
deseaba fervientemente recibir sabiduría para que me dirigiera en un camino que
fuera aceptable al Señor. Y aunque sentía un deseo fuerte de adquirir conocimiento,
estaba dispuesto a someterme a la disposición de la Providencia,
y no me atrevía a pedir nada salvo en completa sumisión a la voluntad Divina,
sabiendo muy bien que si obtenía algo en cualquier otra actitud,
no vendría acompañado de bendición. Finalmente,
estando en recuperación y sintiéndome muy ejercitado en mi mente por ese asunto,
una mañana mientras estaba en la cama,
tuve una manifestación tan clara de la voluntad Divina al respecto,
que no dejó dudas en mi mente acerca del curso que debía seguir,
y entonces procedí a prepararme para ser admitido en la universidad.

Después de eso me recuperé rápidamente, y fui a Danby a ver al maestro antes mencionado,
de quien había oído tan buenas características.
Estaba muy contento con él, como creo que él estaba conmigo.
Él era un hombre religioso y tierno de espíritu,
y me parece que era un amante de los hombres buenos,^
footnote:[Tito 1:8 Traducción Literal de la versión KJV]
en el sentido del apóstol.
Después de estar con él por un tiempo, un vecino que era de su congregación, le dijo:
"`Entiendo que tienes a un hereje contigo,
preparándose para ser admitido en la universidad.`"
Él le respondió:
"`Ojalá toda mi congregación fuera tan hereje como él.`" A lo que su vecino
no respondió. Eso me lo contó él mismo un poco después de que había ocurrido.
Había estado con él seis meses, cuando sus otros estudiantes lo dejaron,
y como no era conveniente para él atenderme a mí solo, me fui a un tal Robert Trett,
en New-Milford, y pasé como seis meses con él,
después de lo cual pensó que yo había aprendido suficiente
como para ser admitido en la universidad.
Por ende, fui a la universidad y pasé una evaluación relacionada con mi aprendizaje,
y fui admitido sin ninguna mención de herejía.

Después de ser admitido procuré mantenerme humilde y vivir en el temor del Señor,
a fin de ser un modelo de humildad.
Deseaba ser útil a la humanidad y procuraba mantenerme
cerca de lo único que podía capacitarme para ello.

Considero adecuado en este punto,
hacer una observación con respecto a algo en lo que era propenso a errar,
hasta que la experiencia me enseñó mejor:
hablar demasiado respecto a la religión en mi propia voluntad y tiempo.
Con el tiempo me di cuenta de que eso tendía a la pobreza, y cuando estaba en grupo,
aprendí a no apresurarme a entrar en ninguna conversación respecto a religión,
ni a ningún otro tema,
sino a estar contento con mantener silencio y ser estimado un tonto,
hasta que se levantara la Verdad,
se presentara claramente un tema y se concediera libertad para la conversación. Entonces
sentía que se me concedía capacidad para hablar para la edificación de otros y también
para mi propia paz y satisfacción. Menciono esto para el beneficio de otros,
estando convencido de que muchos que han tenido experiencia de la Verdad,
y que han experimentado en cierta medida un cambio en el corazón,
han hablado tanto de temas religiosos que sus almas se han vuelto tan estériles,
de modo que "`no ven cuando viene el bien.`"^
footnote:[Jeremías 17:6]

Entonces,
a medida que permanecía en un humilde sentido de
mi propio vacío y buscaba la dirección de la Verdad,
hallaba al Señor cerca por Su Espíritu para instruirme
en todas las cosas que eran necesarias conocer;
que eran manifestadas claramente de tiempo en tiempo, conforme podía sobrellevarlas.

Cuando entré a la universidad mis principios correspondían
generalmente con los sostenidos por los Presbiterianos.
Pero en ese entonces comencé a pensar que era tiempo de examinar por mí mismo,
y que ya no debía confiar ciegamente en el juicio de mis antepasados.
Hallé necesario someter mis principios y prácticas a un estricto escrutinio,
debido a que empecé a dudar de algunos de ellos.
Pero también estaba convencido de que, como una simple criatura racional,
no era en lo absoluto competente para esa tarea sin un Instructor Divino.
Percibí claramente que todo entendimiento correcto en asuntos espirituales
debe proceder de la revelación directa del Espíritu Santo,
y que sin ella no podemos llegar al conocimiento de Dios,
ni de ninguna cosa relacionada con Su reino.

Esta creencia era muy diferente a la que sostenían
las personas con las que profesaba religión,
así que no recibía ninguna ayuda de ellas.
Al contrario, sus conversaciones,
sus predicaciones y sus libros estaban contra mí en esto.
No tenía ninguna ayuda externa salvo la Biblia,
y sabía que no podía entenderla sin la ayuda Divina.
No conocía a ninguna persona que creyera en la Luz
de Cristo en su interior como yo lo hacía,
así que no tenía a quién recurrir para que me instruyera en esa dificultad,
sino únicamente a Él. Pero al estar muy deseoso de conocer la verdad en todas las cosas,
clamaba Al que yo creía que era el único Maestro de Su pueblo,
y a medida que esperaba en Él para recibir instrucción,
mi entendimiento era alumbrado gradualmente como
para percibir muchos errores en mis creencias anteriores,
y para descubrir que la Verdad se oponía a las doctrinas en las que había sido criado.

Lo que más se interponía en mi camino,
y que parecía ser una terrible aflicción para la humanidad
y una gran deshonra para el Dios justo y recto,
era su doctrina de elección y reprobación incondicional; la cual,
según su entendimiento de ella,
dejaba a gran parte de la humanidad sin ninguna esperanza de misericordia,
porque ellos creían que eran el único pueblo del Señor,
y que muy pocos aparte de ellos estaban dentro de los límites de la elección (aunque
creo que había algunos más caritativos entre ellos que extendían un poco más esos límites).
Sintiendo una carga por ese asunto, y teniendo un deseo ferviente de descubrir la verdad,
le plació al Señor abrir mi entendimiento para percibir claramente el error de esa doctrina;
y me fue concedido creer que Cristo, quien "`se dio a Sí Mismo en rescate por todos,`"^
footnote:[1 Timoteo 2:6]
"`quiere que todos los hombres sean salvos y vengan al conocimiento de la Verdad.`"^
footnote:[1 Timoteo 2:4]

Me regocijé en ese descubrimiento,
y cuando estaba plenamente convencido de mi error anterior en ese asunto,
le propuse a uno de mis compañeros de estudio que considerara,
si habíamos estado equivocados o no en ese punto de nuestra creencia.
Razonamos acerca de la pregunta muchas veces,
hasta que él estaba casi convencido de que habíamos estado equivocados en ese asunto.
En ese tiempo él no sabía que mis sentimientos eran diferentes a los suyos,
pero suponía que había propuesto la pregunta solo para debatir
y oír lo que podía decirse a favor y en contra de ella.
Yo intencionalmente le escondí mi verdadera creencia,
porque en ese tiempo entendía que no era prudente exponer mis sentimientos genuinos.

Para el momento en que queríamos dejar de debatir sobre ese tema,
tenía algo nuevo que proponerle a mi amigo.
Cuando estábamos libres de nuestros estudios, entrábamos en debate sobre ese tema, y así,
de tiempo en tiempo, razonábamos el punto hasta que estábamos dispuestos a dejarlo.
Así,
a medida que las cosas se revelaban a mis ojos y mi mente llegaba a estar clara
respecto a cualquier punto doctrinal en oposición a mi creencia anterior,
le proponía que lo considerara y luego razonábamos al respecto,
tanto como pensábamos conveniente.
Continuamos de esta manera,
debatiendo de cuando en cuando sobre varios puntos doctrinales,
hasta que mi oponente estaba parcialmente convencido de las verdades que le planteaba,
e incluso se percató de que yo creía en las doctrinas que le había ofrecido a su consideración.
Pero dado que yo pensaba que no era un tiempo apropiado para hacer públicas mis opiniones,
le pedí que no las expusiera en ese momento, con lo que estuvo de acuerdo.
Por dos o tres años usábamos nuestro tiempo libre para discutir
temas religiosos que eran nuevos para él,
y que yo recientemente había sido convencido de la verdad de ellos.

Antes de ese período había oído de un pueblo llamado Cuáqueros,
pero no conocía a ninguno de ellos.
Dado que nunca había visto ninguno de sus escritos, no sabía qué doctrinas sostenían,
y en verdad puedo atribuir todo mi conocimiento de las cosas
divinas a la manifestación interna de la gracia y la verdad,
a la enseñanza del Espíritu Santo.
Era Cristo, la Luz del mundo, la Vida de los hombres,
el que me abría las Escrituras y me daba discernimiento para entender su significado;
y a medida que era fiel y obediente a las indicaciones de la Verdad,
el Señor me favorecía con descubrimientos más profundos y claros de ella.
En ese estado me sentía deseoso de que otros llegaran a conocer la Verdad,
y seguí compartiendo mi perspectiva de los diferentes temas que se me presentaban,
con mi compañero de estudio antes mencionado.
Razonábamos sobre esos temas, conforme eran puestos bajo consideración,
hasta que habíamos debatido todos los puntos principales discutibles de doctrina.
No recuerdo que hayamos omitido ninguno de los asuntos que Robert Barclay trató en su
[.book-title]#Apología por la Teología Cristiana,#
a pesar de que en ese tiempo no había leído ninguno de sus escritos,
ni había oído de ellos, que yo recuerde.

He mencionado estas cosas para demostrar (según la declaración de Cristo),
que "`el que quiera hacer Su voluntad, conocerá si la doctrina es de Dios,`"^
footnote:[Juan 17:7]
y que no tenemos necesidad de que nadie nos enseñe;
sino que la unción nos enseña todas las cosas.^
footnote:[1 Juan 2:27]
Y aunque mi amigo y yo habíamos debatido todos estos puntos, como conté antes,
a menudo los volvíamos a discutir en nuestro tiempo libre,
y en gran medida llegamos a ser de un mismo sentir en los diferentes temas,
como se verá cuando relate los detalles de nuestra separación final.

En ese entonces había llegado a cierta perspectiva de lo
que era un ministerio falso y una adoración falsa,
que vi que habían sido introducidos en casi todas
las iglesias de la religión Cristiana que conocía;
sin embargo, mi perspectiva en esos dos asuntos no era tan clara,
como lo era en muchos otros que habíamos debatido.
Aunque percibía defectos en el ministerio,
en ese entonces no veía que estaba totalmente errado,
ni sabía que era en su totalidad el "`ministerio de la letra que mata;`"^
footnote:[2 Corintios 3:6]
pero más adelante obtuve una perspectiva y conocimiento más claros de esas cosas.
En aquel tiempo pensaba como niño y entendía como niño, respecto a esos temas.
Y ese también era mi estado respecto a la adoración divina.
No percibía claramente que toda adoración realizada en la voluntad
de la criatura y sin la ayuda directa del Espíritu Santo,
era correctamente llamada "`adoración voluntaria`"^
footnote:[Colosenses 2:23]
e idolatría. Pero con el pasar del tiempo percibí claramente que ese era el caso.
Después de que nuestras mentes ya estaban satisfechas con respecto a esos puntos,
me topé por primera vez con la [.book-title]#Apología# de Barclay.^
footnote:[__Una Apología por la Verdadera Teología Cristiana__ escrita por Robert Barclay,
disponible en www.bibliotecadelosamigos.org, bajo el título __Esta Grande Salvación__.]
Pero ahora debo dejar a mi compañero de clase y nuestras discusiones,
y retroceder un poco.

Cuando tenía como un año en la universidad,
el rector me mandó a llamar a su casa para conversar conmigo sobre
algunos rumores que habían estado circulando de que yo era un hereje.
Después de sentarme a su lado según su petición,
me dijo que deseaba escuchar de mi propia boca un relato de mi estado.
Dijo que no era por ningún descontento en su mente con respecto a mí,
porque él estaba tan complacido con mi conducta desde
que me había convertido en uno de sus miembros,
que creía que los rumores se debían principalmente a malentendidos,
ignorancia y mala voluntad, y que él deseaba saber por mí el motivo de esos rumores.
Esa fue la sustancia de su comunicación. Yo respondí
que si a él le placía ser paciente conmigo,
le daría un relato completo y sería tan breve como pudiera a fin de ser entendido.
Entonces le conté mis primeros pasos en mi viaje religioso, mis luchas,
ejercicios y experiencias internos hasta ese día,
lo cual supongo que me tomó como una hora y media.
Durante todo ese tiempo él estuvo muy quieto y atento,
sin hacerme la más mínima interrupción. Pensé que
me oía con mucha satisfacción. Cuando concluí,
nos quedamos en silencio por un tiempo.
Él parecía estar tan afectado que no podía hablar con facilidad.
Después de recuperarse, finalmente dijo: "`Ferris,
bendigo a Dios por darte ojos para ver lo que pocos ven.`"
No me habló nada más,
sino solo para decirme que estaba muy contento con la oportunidad y entonces me despidió.

No creo haberle ocultado ninguno de los principios que sostenía durante
el tiempo que había sido considerado "`un hereje,`" pero no le revelé
todas las perspectivas que tenía en el momento que hablé con él,
porque estaba consciente de que no las podía sobrellevar.
Él era un cristiano sincero y un amante de los hombres buenos,
y después mostró un interés muy especial por mí,
al decir más a mi favor de lo que yo pensaba que merecía,
aunque no más de lo que él creía ser verdadero.
Y ese fue el caso con muchos otros,
cuyas expectativas de que yo iba a ser muy útil en el futuro,
de alguna manera se habían levantado,
y por eso era muy estimado por las personas más respetadas.
Pero al mantenerme humilde y pequeño ante mis ojos,
y viendo mi propia debilidad y enfermedades,
fui preservado de las trampas de la popularidad,
aunque ellos hicieron que mis pruebas fueran más grandes,
como se mostrará en el lugar adecuado.

Después de esa entrevista con el rector, continué mis estudios,
lo cual hacía con diligencia,
deseando ser hallado en el camino de mi deber en todos los aspectos,
a fin de que una bendición acompañara mi empresa.
Era muy cuidadoso con mis pensamientos, palabras y acciones,
procurando ser de ejemplo y ayuda para todos los que estaban alrededor de mí.

Entonces comencé a pensar muchísimo más en asuntos religiosos.
Las doctrinas que me habían enseñado y la forma de adoración en la que había sido educado,
eran asuntos que me preocupaban.
Deseaba cerciorarme si soportarían un estricto escrutinio.
Al probarlas, encontré que muchas de ellas eran defectuosas,
y de aquí surgieron los muchos debates que tuve con mi compañero de clase,
como relaté anteriormente.

Como a mitad del último año de mi residencia en la universidad,
me topé con la [.book-title]#Apología# de Barclay, y después de leerla,
dejé que mi compañero (con quien antes había discutido
las doctrinas consideradas ahí) la examinara.
Él leyó la obra atentamente e hizo muy pocas o ninguna objeción,
sino más bien me dijo que los argumentos de Barclay eran irrefutables.
Varios otros de los estudiantes que reflexionaban más las cosas, a quienes les
presté el libro, después de hacerlo, hicieron el mismo reconocimiento,
haciendo muy poca objeción u oposición a los razonamientos de su autor.

Continué en la universidad hasta que ya estaba cerca el tiempo de recibir mi título,
y al estar convencido de los errores de mi educación con respecto
a las doctrinas que sosteníamos y a la adoración que realizábamos,
entendí que era el momento de considerar qué era lo mejor para mí. Y finalmente,
habiendo sido favorecido con la capacidad de ver que una calificación o comisión
que proviene del hombre no era suficiente para el ministerio del evangelio,
decidí no tomar sus títulos, ni depender de su autoridad.

Pero aunque estaba de acuerdo con Barclay en temas doctrinales,
todavía no sabía si podía unirme a los Cuáqueros, o a algún otro pueblo que conociera.
Continué siendo miembro de la sociedad Presbiteriana,
y seguí asistiendo a sus reuniones y participando de su
pan y vino--aunque no me sentía libre de cantar con ellos,
ya que por un tiempo no estuve en condiciones para cantar; además,
no me parecía un sacrificio aceptable, o algo parecido a la adoración divina,
que una multitud mixta cantara de cosas de las que
no conocían absolutamente nada por experiencia.
Mi ejercicio mental se incrementaba diariamente,
porque sentía que se acercaba el tiempo en que debía dejarlos.
Ese fue un día de gran prueba para mí. Porque,
a pesar de que al comienzo de mi progreso religioso abandoné todos los
deleites y vanidades juveniles con los que me entretenía en el pasado,
y Dios me había capacitado para ponerlos bajo mis pies,
teniendo la esperanza de nunca encontrar otra vez este tipo de dificultades, aun así,
veía que el yo no había sido crucificado suficientemente
en mí. Ser derribado del pináculo de honor,
ser estimado un tonto y hollado bajo los pies de altos y bajos, ricos y pobres,
aprendidos e ignorantes, era algo difícil de soportar para mí. Como mencioné antes,
yo era muy estimado; en verdad,
mucho más de lo que merecía. Sabía que algunas personas
tenían expectativas exageradas respecto a mi futura utilidad,
y que si dejaba la universidad (como pensaba que era mi deber hacer)
mi reputación se hundiría y mis honores quedarían en el polvo.
Y entonces, en lugar de ser querido y exaltado, sería rechazado y despreciado.

Pero también tenía otras dificultades que encarar.
Mi padre tenía mucha esperanza de que yo fuera un honor para él y su familia.
Había prometido prepararme para el mundo de la mejor manera que le permitieran sus circunstancias.
Yo sabía que si era obediente a las convicciones de mi deber,
él lo tomaría como una desgracia para mi familia y conocidos,
y que era más probable que me echara de su casa a que me ayudara de alguna manera.
Aparte de eso, yo había oído de una vacante para un ministro,
y que las personas esperaban que yo la ocupara.
La congregación era numerosa,
el salario que se ofrecía era mayor que todos los que conocía en esa parte del país,
y me habían dicho que los directores de la universidad
habían sido consultados respecto a ese asunto.

En ese momento sabía que para cumplir con mi sentido del deber,
debía "`tomar la cruz`" y salir al mundo sin provisión;
porque no tenía muchos bienes propios, nada que esperar de mi padre,
ni ningún salario para sustentarme.
Muchos me considerarían como "`el desecho de todos,`"^
footnote:[1 Corintios 4:13]
el bueno para nada.

Seguí luchando bajo una fuerte sensación de todas esas dificultades.
La pobreza y la desgracia me miraban a la cara;
y dado que no tenía a nadie a quien pudiera dar a conocer
mi angustia y desaliento sino únicamente al Señor,
ni ningún otro a quien le pudiera pedir consejo,
clamaba incesantemente a Él por sabiduría, fuerza y fortaleza,
pidiéndole que me favoreciera con un conocimiento claro de mi deber
y me capacitara para obedecerlo fielmente en todas las cosas.

En ese tiempo mis pruebas y dificultades eran tan numerosas,
que estaba listo para concluir con Job que "`en mi nido moriría.`"^
footnote:[Job 29:18]
Tenía miedo de que nunca fuera capaz de entregar todos los intereses,
los honores y la reputación que tenía en el mundo,
de aceptar vivir en una condición de pobreza y de
caer en la desgracia de ser considerado hereje.
Esas dificultades eran presentadas ante mi vista y magnificadas
al grado más alto de lo que cualquiera pudiera imaginar.
En el momento más intenso de mi angustia,
entré en mi habitación y derramé mi queja delante del Señor de esta manera:
"`¡Oh Señor! ¡No sé qué hacer en este día de profunda angustia
y ansiedad de alma! ¡No estoy suficientemente claro respecto a
mi deber de emprender y realizar este asunto tan importante.
Todo lo que tengo de valor en este mundo y también mi felicidad eterna,
parecen estar en juego ahora!`"
En verdad, mi situación presente parecía tan importante,
que si yo tomaba un curso equivocado y una dirección incorrecta,
todo podría perderse para siempre.
Y si era guiado por el espíritu de error y confusión,
ofendería a mi Hacedor y a mis prójimos,
permanecería para siempre en un oscuro desierto y nunca
recuperaría el favor de Dios o de los buenos hombres.

Las tinieblas se apoderaron de mí a tal punto,
que me vi en la situación de Juan el Bautista cuando
envió a dos de sus discípulos a preguntarle a Cristo:
"`¿Eres Tú Aquel que había de venir, o esperaremos a otro?`"^
footnote:[Juan 11:3]
Yo estaba a punto de caer en desesperación y de concluir,
que estaba totalmente equivocado al proponerme dar un paso tan contrario a la razón,
como entonces me parecía que era ese.
Así derramé mi queja y lloré delante el Señor. No tenía de quién depender sino de Él,
ni ningún otro a quién pedir consejo en mis angustiantes circunstancias.
Dependía completamente de Él para recibir sabiduría
y dirección en esa situación de prueba y aflicción.

Es difícil explicar (y no tengo la capacidad de expresar)
la ansiedad de mi mente en ese tiempo de prueba;
porque todas las cosas de valor parecían en peligro de perderse totalmente.
Sin embargo, clamé al Señor pidiéndole ayuda e hice pacto con Él;
le dije que si a Él le placía dirigirme en el camino que era seguro para mi seguir,
manifestarme Su voluntad en él y concederme ayuda para cumplir con mis deberes,
yo entregaría todo a Su disposición, obedecería Su voluntad,
no razonaría más con carne y sangre,
y pondría mi confianza en Su providencia para mi mantenimiento y reputación en el mundo,
y para todo lo demás que Él considerara mejor y más
conveniente para mí. Porque en ese entonces,
estaba claramente convencido de que si no entregaba todo
cuando me fuera evidentemente manifestado que era mi deber,
no tenía nada que esperar sino muerte, en relación con mi condición espiritual.

Mientras lamentaba mi condición de esa manera delante
del Señor y esperaba en Él Su dirección,
con oraciones fervientes pidiendo Su ayuda y sabiduría
para que me guiaran en el camino correcto,
le plació bondadosamente mostrarme que Él estaba tratando de sacar la iglesia del desierto,
o del estado errante,
en el que había estado por mucho tiempo destituida
del verdadero Guía. Y me hizo saber claramente,
que era Su voluntad que yo saliera y fuera un instrumento
en Su mano para el cumplimiento de ese propósito.

Tan pronto estuve satisfecho con respecto a esos puntos,
no razoné más con carne y sangre,
sino que me entregué inmediatamente a la visión celestial.
Entonces fui al director principal de la universidad y obtuve su permiso de ir a casa;
pero no le dije a nadie las razones por las que lo hice.

Ese fue un tiempo de prueba, porque estaba a punto de dar un paso importante.
Como Gedeón,
estaba deseoso de "`probar otra vez con el vellón,`" esperar en
retiro Su sabiduría y considerar cuidadosamente esa importante
tarea que entonces sentía fuertemente sobre mi mente.
Después de permanecer en casa como tres semanas,
la voluntad de mi Maestro Divino en relación con mi salida
de la universidad me fue manifestada satisfactoriamente.
Sin dar a conocer mi propósito,
regresé a la universidad y puse mis asuntos en orden para dejarla.
Mientras me preparaba para hacerlo,
se difundió un rumor entre los estudiantes de que
me había "`vuelto Cuáquero`" y que iba a dejarlos,
sin embargo,
ninguno de ellos profirió una palabra dura o de maldición contra mí. El rector,
Elisha Williams, se tomó un tiempo para conversar conmigo.
Él fue muy moderado,
pero dijo que lamentaba mi decisión y que hasta ese
momento había tenido una buena opinión de mí,
y la expectativa de que iba a ser útil en mi día;
pero que ahora sus esperanzas habían sido frustradas en gran medida.
Conversamos mucho sobre ese asunto, y me dio a entender que no me daba por perdido.
Se mostró serio y nos despedimos como buenos amigos.

Cuando se acercaba el tiempo de mi salida de la universidad,
estando totalmente entregado a la voluntad del Señor,
la nube fue removida de mi tabernáculo, mi visión se aclaró,
mi coraje regresó y todos los montes (cuyas cimas muy recientemente
parecían alcanzar las nubes) fueron nivelados como una llanura.
En verdad, sentí como si el mar hubiera retrocedido,
de modo que no había nada que interrumpiera mi paso.
Crucé sobre todo como en tierra seca y ni a un perro se le permitió mover
su lengua contra mí. Entonces mi alma se llenó de alabanzas vivas,
acciones de gracias y regocijo en el Señor, quien había triunfado gloriosamente.
Él era mi fuerza,
mi cántico y mi salvación. Los abismos cubrieron a mis enemigos
y se hundieron hasta el fondo como una piedra.
La diestra del Señor fue gloriosa en poder y canté Sus alabanzas, porque Él era digno,
al haber hecho grandes cosas por mí.

Antes de dejar la universidad, le conté mis intenciones al rector,
y le dije que no sabía si algún día regresaría,
pero que si cambiaba de parecer y quería recibir un título--si
se me permitía--quizás volvería con esa intención;
y que si decidía no regresar,
le escribiría y le daría las razones de mi decisión. Él respondió que yo sería
muy bienvenido y que sería un placer para ellos concederme un título.

Mientras estaba preparándome para mi viaje,
mi compañero (antes mencionado) que deseaba cabalgar un día conmigo,
obtuvo permiso de la universidad,
aunque el director le advirtió que yo podía inculcarle malos principios y desviarlo.
Mi amigo respondió a eso diciendo:
"`He vivido con él la mayor parte del tiempo desde que vine a la universidad,
y creo que no me ha hecho ningún daño, más bien todo lo contrario.`"
Entonces, después de despedirnos de todos, nos fuimos.

Consideré un favor de Dios que uno de mis compañeros de estudio que tenía
buena reputación y estaba entre los más estimados en la universidad,
estuviera dispuesto a tomar la cruz al punto de acompañarme a mí,
que era considerado un hereje o un Cuáquero.
Pero una medida de amor que sentía por mí,
hizo que no tuviera miedo de ninguna vergüenza o desgracia que le pudiera sobrevenir.

Mientras cabalgábamos,
discutimos todas las doctrinas que habíamos debatido anteriormente,
y él parecía tan convencido de la verdad de mis pensamientos como yo.
Al anochecer, cuando estábamos a punto de separarnos, él dijo: "`Ferris,
creo que estás en lo correcto al dejar la universidad.
Creo que tus principios son sanos y buenos; pero en este momento,
no veo que yo sea llamado a hacer lo que tú has hecho.
Si en algún momento después, yo viera que es mi deber seguir tu ejemplo,
me propongo no hacer mi propia voluntad,
sino someterme y obedecer la voluntad de mi Maestro.`"
Nos despedimos y nunca más lo volví a ver;
pero después oí que seguir mi ejemplo era una cruz demasiado pesada de llevar para él.
Se dedicó a predicar entre los Presbiterianos para ganarse la vida y nunca los dejó,
que yo sepa.

Después de despedirme de mi compañero, fui a New-Milford,
donde residían mis padres y familiares.
Como tres semanas después,
fui a una Reunión Anual del pueblo llamado Cuáqueros en Long-Island,
con la intención de descubrir si eran o no un pueblo vivo;
porque lo que yo deseaba encontrar era un pueblo que estuviera vivo espiritualmente.
Por varios años había pensado que debía existir un pueblo así,
un pueblo que tuviera vida en su interior y que abundara en amor unos para con otros,
como los Cristianos primitivos;
un pueblo que supiera que había pasado de muerte a vida por su amor a los hermanos.
Y allí, en la Reunión Anual,
fui fortalecido e incluso recibí mayor confirmación
de que había hecho lo correcto al dejar la universidad;
porque encontré un pueblo vivo, humilde, lleno de amor y de buenas obras,
un cuerpo de Cristianos como jamás había visto.
Me regocijé grandemente al encontrar lo que había estado buscando,
y muy pronto reconocí que eran el pueblo del Señor, la verdadera iglesia de Cristo,
según Su propia descripción, donde dice:
"`En esto conocerán todos que sois Mis discípulos,
si tuviereis amor los unos con los otros.`"^
footnote:[Juan 13:35]

También me di cuenta de que ellos sostenían y creían las mismas
doctrinas que el Espíritu Santo me había manifestado directamente;
que eran las mismas que Robert Barclay había establecido y defendido
bien en su [.book-title]#Apología.# Antes de haber leído esa obra,
no sabía que había un pueblo sobre la tierra que creyera
y viviera en la Verdad como Barclay lo describía;
pero allí encontré una numerosa sociedad, cuyos miembros sostenían las mismas verdades,
llevaban una vida humilde de negación a sí mismos, propia del carácter de los Cristianos.
Estaba indudablemente convencido de que su adoración era en espíritu y verdad,
y que ellos eran esos adoradores que el Padre buscaba y reconocía. Y estaba convencido
(sin ninguna duda) de que ellos predicaban el Evangelio en la demostración del Espíritu;
porque se sentía que la autoridad divina acompañaba su ministerio.
Ellos no eran como los escribas que yo había estado escuchando toda mi vida,
que no tenían ni comisión ni autoridad salvo aquella que era recibida del hombre;
siendo como aquellos que el Señor nunca envió, y que por lo tanto,
no podían ser de provecho al pueblo a quien decían enseñar. Ahora veía
claramente la diferencia entre los ministerios hechos por el hombre,
y aquellos a quienes el Señor capacita y envía a Su campo de cosecha,
la diferencia entre el trigo y la cizaña. Y en verdad era impactante para mí
reflexionar sobre cuánto tiempo había estado sometido a un ministerio formal,
seco y sin vida.

En la reunión antes mencionada, había varios ministros eminentes de Europa,
tanto masculinos como femeninos.
Allí oí a mujeres predicar el evangelio en la autoridad Divina de la Verdad,
superando por mucho a todos los eruditos rabinos que había escuchado.
Eso no fue tan extraño para mí como podría haber sido para otros,
porque había visto antes, por la directa manifestación de la gracia y la verdad,
que las mujeres (al igual que a los hombres) podían ser revestidas del poder del evangelio;
y que en la dispensación del evangelio,
el Espíritu era derramado sobre hijas como también
sobre hijos a fin de que pudieran profetizar.
Y aunque nunca antes había oído a una mujer predicar,
en ese momento me regocijé de ver la profecía de Joel cumplida.

Después de regresar a casa de la Reunión Anual,
le escribí una carta al rector de la universidad,
informándole que había decidido no volver,
y que no podía recibir con libertad ninguna autoridad
para ser ministro que el hombre pudiera otorgar.
También le informé que (después de haberlos dejado) había escuchado a mujeres predicar
el evangelio mucho mejor que cualquiera de los hombres cultos que había oído.

Después de dejar la universidad y de separarme del pueblo entre el cual había sido educado,
vi un gran motivo para agradecerle al Autor de toda bondad,
por haberme revelado los errores de mi juventud y la falsedad de
muchas doctrinas que me habían sido inculcadas en mi educación,
y por llevarme a conocer Su verdad y a Su pueblo, de modo tal,
que no me quedó ninguna duda.
En ese momento se volvió mi principal interés ser capacitado para caminar en
la verdad y experimentar al Espíritu Santo como mi guía en mi camino.

En ese estado admiré la ilimitada bondad,
la infinita amabilidad y la tierna misericordia del bondadoso Dios,
al llevar acabo mi reciente redención;
especialmente al considerar cuán tempestuosas estaban los mares,
y cómo pasaban las olas sobre mí,
y cómo los montes de oposición levantaban sus elevadas cimas, todo para impedir mi paso;
y luego, en poco tiempo, cómo fueron acallados y calmados los vientos y los mares,
y cómo las montañas se convirtieron en perfecta llanura.
Ciertamente, hallé un gran motivo para cantar en las orillas de la redención,
como el que tuvo Israel después de que habían pasado a través del mar por tierra seca,
y habían volteado sus rostros para ver que sus enemigos yacían muertos en la orilla.
Me regocijé en el Señor y le canté alabanzas Al que
había hecho cosas maravillosas por mí,
cuando me sometí a la cruz de Cristo;
porque Él me había dado a conocer Su bendita verdad,
y finalmente me había dado la capacidad de hollar al mundo bajo mis pies,
con todas sus riquezas, honores y placeres,
aunque todos los hombres me consideraran necio.
Por esos favores me sentía grandemente comprometido con mi bondadoso Benefactor.

Ahora volveré a la primera parte de mi relato,
y contaré algo sobre cómo mi familia y parientes
me recibieron después de regresar de la universidad.
Luego de que me despedí de mi compañero en el camino,
escuché que mi padre había recibido información respecto a mis
intenciones y que estaba muy descontento con mi proceder,
y que decía: "`Si la información que he oído es verdad,
no quiero que venga más a mi casa.`"
Al ser informado de eso, fui a casa de mi hermano,
pero después de algunos días fui a ver a mi padre.
Él no quiso hablar conmigo, sino que se volteó, me ignoró y se fue.
Unos pocos días después fui por segunda vez, pero él todavía se negaba a hablarme.
Luego de unos pocos días más, fui por tercera vez y me lo encontré en la puerta.
Le pregunté sobre su salud,
mientras me quitaba mi sombrero (porque en ese momento todavía no había sido
convencido de la necesidad de dar testimonio contra el honor del sombrero).
Él me respondió que no estaba muy bien y se alejó otra vez.
Entonces entré a la casa y cuando mi padre regresó,
nos sentamos y entablamos conversación. Dijo que había oído
que yo había dejado la universidad y me había hecho Cuáquero.
Le respondí que durante algunos años había estado procurando seguir a mi Líder Divino,
y que todavía procuraba prestarle atención al mismo
Guía y seguirlo a donde quiera que me llevara.
Entonces le dije que comprendía que Él me había llevado a dejar
la universidad y a abandonar el camino de mi educación,
y que era posible que en algún momento dicho Guía
me llevara a unirme al pueblo llamado Cuáquero,
pero que todavía no sabía mucho de ellos.

Después de pasar un tiempo conversando cosas como esas,
mi padre me preguntó qué necesidad había de dejar el camino de mi educación;
"`Porque,`" dijo,
"`el Señor te ha favorecido y ha estado contigo en la religión Presbiteriana,
y si tú continúas temiendo y sirviendo al Señor en ese camino, te irá bien;
y sin ninguna duda, terminarás en paz.`"
Le respondí que era cierto que había sido favorecido en mi profesión religiosa anterior,
porque el Señor había estado cerca de mí y Su presencia viva conmigo.
Le dije que Él me había dirigido y llevado por Su buen Espíritu,
y me había revelado Su voluntad mucho más allá de lo que merecía o podía esperar;
y que todavía deseaba seguir a ese Maestro que nunca me había desviado,
sino que me había llevado paso a paso, de un grado de experiencia a otro,
hasta que me había sentido obligado a dejar la universidad y a
dar testimonio contra la profesión religiosa formal que había practicado,
y que así Él me había conducido hasta el momento presente.

Así conversamos por algunas horas,
mi padre hizo varias objeciones contra los Cuáqueros
y contra el hecho de que me uniera a ellos.
Pero, por la ayuda divina (con la cual creo que fui favorecido),
fui capaz de responder plenamente a todas sus objeciones,
de modo que él quiso dejar el tema,
y se volvió más moderado y aparentemente más aliviado mentalmente.
Desde ese tiempo en adelante, durante el resto de su vida,
aunque tuvo muchas oportunidades, nunca volvió a discutir conmigo sobre temas religiosos,
sino que siempre fue amable y amoroso.
Pienso que él concluyó que todavía podría irme bien
en el camino en el que me había hallado,
y por lo tanto se mantuvo satisfecho.

Después de estar en casa por algún tiempo,
surgieron nuevas objeciones en mi mente contra el cumplimiento
de las costumbres de las personas entre las que vivía;
costumbres como inclinarse y arrastrar el pie, quitándose el sombrero y diciendo:
"`Su servidor, señor, señora,
etc.`" y el uso del lenguaje gramaticalmente incorrecto
y corrupto del "`ustedes`" para una sola persona.^
footnote:[Como ya se ha mencionado en el primer volumen de
[.book-title]#La Verdad en lo Íntimo,# a partir del siglo XVII,
el uso correcto y simple de "`tú`" y "`usted`" para una
sola persona empezó a dar paso a "`vosotros`" y "`ustedes.`"
La mayoría de los angloparlantes modernos desconocen que las palabras
"`you`" y "`your`" eran originalmente pronombres plurales que se
utilizaban sólo para dirigirse a dos o más personas,
mientras que "`thee`" y "`thou`" se usaban para dirigirse a una sola persona.
En el siglo XVII,
se puso de moda (originalmente con el fin de mostrar honor o adulación)
utilizar el plural "`you`" y "`your`" ("`ustedes`" y "`vosotros`")
para dirigirse a personas de mayor estatus social,
mientras que "`thee`" y "`thou`" ("`tú`" y "`usted`") se reservaban para los sirvientes,
los niños o las personas de menor posición social o económica.
Los amigos se ciñeron a lo que entonces se consideraba "`lenguaje simple`" (utilizar
los pronombres "`thee`" y "`thou`" ("`tú`" y "`usted`") para una sola persona,
y "`you`" y "`your`" ("`ustedes`" y "`vosotros`") para dos o más,
en lugar de mostrar preferencia al dirigirse a ciertos individuos en plural.
Esto parece algo insignificante para el lector del siglo XXI,
pero muchos miles de los primeros Amigos fueron insultados, golpeados,
encarcelados y hasta colgados por negarse a conformarse a esas costumbres externas.]
Aunque en los años anteriores había experimentado varias
pruebas y pensaba que había aprendido muchas lecciones duras,
en ese momento, descubrí mucho dentro de mí que todavía debía ser crucificado,
y vi que tenía que aprender muchas cosas.
Negarme a usar el lenguaje plural para dirigirme a una sola persona,
aunque parezca algo pequeño,
resultó ser algo muy difícil de cumplir para mí. Estaba convencido de que el
modo común de hablarle en plural a una sola persona no era conforme a las Escrituras,
y que era una violación de las reglas de gramática.
En efecto, yo sabía que el orgullo del hombre había introducido esa costumbre,
sin embargo,
también quería creer que no era necesario ponerme en ridículo
ante todos los que me rodeaban por un asunto tan irrelevante.
Por lo tanto,
mientras no sentí la necesidad impuesta sobre mí de tomar la cruz en ese aspecto,
seguí usando el lenguaje de mi educación,
aunque usaba los cumplidos halagadores más esporádicamente,
porque dejar de usarlos no era tan notorio.
Sin embargo,
no pasó mucho tiempo antes de que sintiera que era
mi deber decir tú y usted a cada persona individual.

Sin embargo, encontré una inclinación o tentación en mí,
de dirigir mis conversaciones de tal modo que evadiera ese modo de hablar;
pero eso no me dio paz.
A pesar de cuán pequeño me parecía ese asunto,
no podía sentirme aliviado sin ser completamente fiel en cada aspecto;
y cuando mi deber en ese asunto fue manifestado claramente,
no razoné más con carne y sangre,
sino que me sometí al requerimiento del Señor. Era una regla para
mí nunca hacer nada de este tipo en imitación de otros hombres;
pero, siempre que algo era requerido de mí, entonces me sometía y así obtenía paz.

Alrededor de ese tiempo, varios estudiantes que venían de la universidad,
me invitaron a acompañarlos en una visita al ministro de nuestro pueblo, y fui con ellos.
Estábamos caminando con nuestros sombreros bajo nuestros brazos y así entramos en la casa.
Justo cuando estábamos a punto de despedirnos,
sentí que se me requería dar un testimonio contra la costumbre del honor del sombrero.
Así que me levanté, me puse mi sombrero,
fui al sacerdote y me despedí de él sin tocar mi sombrero o inclinar mi cuerpo.
Esa fue la primera vez que negué estos cumplidos, fue una prueba fuerte para mí,
y me pareció increíble que me fuera requerida en un momento como ese,
y con esa compañía. Pero ni el sacerdote ni ninguno
de mis compañeros tomaron en cuenta eso,
como para hacer algún comentario.
Mi obediencia me proporcionó mucha paz,
y por entregarme a esos movimientos internos de mi Guía certero en cosas pequeñas,
yo obtenía fuerza y recibía cada vez más confirmación de
que estaba en lo correcto al haber hecho ese cambio.

Entonces empecé a dejar algunas de las superfluidades
de mi vestimenta y a parecerme más a un Cuáquero,
creyendo que se me requería no esconderme en ningún aspecto,
sino más bien dar testimonio abiertamente de la verdad,
en la medida que me era manifestada con claridad.
En ese entonces no me sorprendía que las personas se maravillaran
de nuestra locura (como suponían que era),
al convertirnos en el hazmerreír y en la comidilla
de todos por nuestra peculiaridad e inconformidad;
porque así me había parecido a mí por un corto tiempo
antes de que fuera movido a someterme a ello.
Yo amaba el honor y la estima de los hombres tanto como cualquier otro,
y hubiera preferido disfrutar de eso,
si hubiera podido hacerlo junto con paz en mi mente.
Pero eso no es permitido en la escuela de Cristo,
donde no se puede hacer nada sin negarnos a nosotros mismos y sin tomar la cruz diaria.
Y si por nuestra parte hay una completa sumisión en todas las cosas,
puedo decir por experiencia, que nuestra paz fluirá como un río.

Habiendo dejado la universidad sin tomar un título,
veía que era probable que no tuviera ningún salario del que depender para subsistir.
Había ofendido a mi padre, y por supuesto no tenía nada que esperar de él;
y tenía muy poco de mi propiedad para sustentarme.
Y entonces, al llegar a los veinticinco años de edad,
comencé a pensar que era necesario hacer algunos esfuerzos para obtener un sustento.
Por varios años antes de ese período, había pensado en irme a vivir a Pensilvania,
y en ese momento se me abrió esa posibilidad tan claramente,
que estaba inclinado a creer que era mi deber ir allá. Por consiguiente,
me preparé y fui en compañía de tres amigos ministros de Europa,
quienes entonces estaban en una visita religiosa a América.
Llegamos a Filadelfia a mediados del sexto mes, 1733.

[.offset]
Aquí termina la parte de mi narración que escribí en latín cuando era joven.

[.asterism]
'''

__David Ferris siguió adelante y se convirtió en un
ministro fiel y útil en la Sociedad de Amigos,
viajando frecuentemente con Samuel Neale y otros ministros eminentes,
pero no antes de haber luchado por un tiempo muy largo con un sentido
de insuficiencia para la obra para la que el Señor lo había llamado.
Por casi veinte años sintió al Espíritu moviéndolo a levantarse
y hablarle al pueblo del Señor cuando estaban reunidos para adorar,
pero, como Moisés, seguía diciendo en su corazón: "`Oh mi Señor,
quien soy yo para hablarle a Tu pueblo.
Por favor envía por mano de quien has de enviar!`"
Pero finalmente,
a través del consejo y la intercesión de ese muy respetado ministro del evangelio,
Comfort Collins, a los cuarenta y ocho años,
finalmente se entregó a su llamado a declarar las
maravillosas obras del Señor. "`Así,`" dice él,
"`finalmente fui levantado de ese horrible pozo cavado por mí mismo,
y fui tan absorbido en el amor y en la misericordia de mi Benefactor celestial,
que me llené de agradecimiento y alabanzas, acompañados con un deseo de que en el futuro,
pudiera diligentemente velar y esperar el señalamiento de
Su dedo santo para cada servicio que le placiera asignarme;
para que de aquí en adelante no perdiera ninguna oportunidad de manifestarle mi gratitud,
al obedecer Su voluntad.`"
Dejó esta vida el cinco del doceavo mes, de 1779, con más de setenta y dos años de edad,
habiendo sido un ministro eficaz alrededor de veinticuatro años.__
